FROM python:3.8-alpine
WORKDIR /project
COPY ./flask_server/src/requirements_dev.txt /project
RUN apk add --no-cache mariadb-connector-c-dev ;\
    apk add --no-cache --virtual .build-deps \
        build-base \
        mariadb-dev ;\
    pip install mysqlclient;\
    apk del .build-deps
RUN pip install -r requirements_dev.txt
